<?php

namespace backend\assets;
use yii\web\View;

/**
 * 后台模板资源包。
 */
class HuiAsset extends AppAsset
{

    public $basePath = '@webroot';
    public $baseUrl = '@web';
    const THEME = 'default';
    public $css = [
        'theme/' . self::THEME . '/H-ui.admin/static/h-ui/css/H-ui.min.css',
        'theme/' . self::THEME . '/H-ui.admin/static/h-ui.admin/css/H-ui.admin.css',
        'theme/' . self::THEME . '/H-ui.admin/lib/Hui-iconfont/1.0.8/iconfont.css',
        'theme/' . self::THEME . '/H-ui.admin/static/h-ui.admin/skin/default/skin.css?id=skin',
        'theme/' . self::THEME . '/H-ui.admin/static/h-ui.admin/css/style.css',
        'theme/' . self::THEME . '/H-ui.admin/lib/webuploader/0.1.5/webuploader.css'
    ];
    public $js = [
        'theme/' . self::THEME . '/H-ui.admin/lib/layer/2.4/layer.js',
        'theme/' . self::THEME . '/H-ui.admin/static/h-ui/js/H-ui.js',
//        'theme/' . self::THEME . '/H-ui.admin/static/h-ui.admin/js/H-ui.admin.min.js',
        'theme/' . self::THEME . '/H-ui.admin/static/h-ui.admin/js/H-ui.admin.js',
        'theme/' . self::THEME . '/H-ui.admin/lib/html5shiv.js',
        'theme/' . self::THEME . '/H-ui.admin/lib/respond.min.js',
        'theme/' . self::THEME . '/H-ui.admin/lib/My97DatePicker/4.8/WdatePicker.js',
        'theme/' . self::THEME . '/H-ui.admin/lib/laypage/1.2/laypage.js',
        'theme/' . self::THEME . '/H-ui.admin/lib/webuploader/0.1.5/webuploader.min.js',
        'theme/' . self::THEME . '/H-ui.admin/lib/jquery.validation/1.14.0/jquery.validate.js',
    ];

    public $jsOptions = [
        'position' => View::POS_END
    ];

    //依赖包
    public $depends = [
        'yii\web\YiiAsset',//主要包含yii.js 文件，该文件完成模块JavaScript代码组织功能， 也为 data-method 和 data-confirm属性提供特别支持和其他有用的功能
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

}
