<?php
namespace backend\controllers;

use backend\models\AB;
use backend\models\Employee;
use common\models\Functions;
use common\models\Status;
use Yii;
use yii\web\Controller;
use backend\models\Module;
use yii\web\Response;

/**
 * Site controller
 */
class CommonController extends Controller
{
    public $layout = 'main';
//    public $layout = false;
    private $moduleModel;
    public $enableCsrfValidation = false;
    public $businessId = 1;


    public function __construct($id, $module, array $config = [])
    {
        parent::__construct($id, $module, $config);
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $view = Yii::$app->getView();
        $view->params['web_name'] = Functions::getCommonByKey('web_name');
        //总体布局设置用户信息
        $id = Yii::$app->user->getId();
        $view->params['employeeInfo'] = Employee::getOneInfoById($id,'employee_name');
        $view->params['imgPath'] = Functions::getCommonByKey('img_url');
    }

    /**
     * 在程序执行之前，对访问的方法进行权限验证.
     * @param \yii\base\Action $action
     * @return bool
     * @throws ForbiddenHttpException
     */
    public function beforeAction($action)
    {
        //isGuest为真表示访客，需要进行登录操作
        //isGuest非真表示认证用户，认证过的用户表示已经登录了，跳转到主页面
        if (Yii::$app->user->isGuest) {
            $this->redirect(["login/login"]); return true;
        }
        $result = AB::checkABInfo();
        if ($result['isLock']['status'] || ! $result['isStart']['status'] || $result['isEnd']['status']) {
            $this->redirect(["login/login"]); return true;
        }
        //网站是否关闭
        $isClose = Functions::getCommonByKey('web_close_on_off');
        if ($isClose == 2) {
            $this->redirect(["login/logout"]); return true;
        }
        if (!parent::beforeAction($action)) {
            return false;
        }
        return true;
    }

    /**
     * 获取关联的菜单
     * 用于修改权限
     * @return mixed
     */
    public function actionRelChoose()
    {
        $id = intval(Yii::$app->request->post('id'));
        $this->returnJson();
        $moduleModel = new Module();
        return $moduleModel->relChoose($id);
    }

    //返回json格式的数据
    public function returnJson() {
        Yii::$app->response->format = Response::FORMAT_JSON;
    }

    //通知弹窗
    public function actionNotifyModal()
    {
        $message = Yii::$app->request->get('message');
        return $this->renderAjax('//common-modal/modal_notify',['message' => $message]);
    }

    //警告弹窗
    public function actionWarningModal()
    {
        $message = Yii::$app->request->get('message');
        return $this->renderAjax('//common-modal/modal_warning',['message' => $message]);
    }
}
