<?php
namespace common\models;

use Yii;
use yii\db\ActiveRecord;

class Operate extends Common
{
    public $_db = null;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->_db = Yii::$app->db;
    }

    public static function tableName()
    {
        return '{{%operate_log}}'; // TODO: Change the autogenerated stub
    }

    /**
     * 记录操作日志
     * @param string $operateMessage
     * @param array  $operateData
     * @param array  $operateWhere
     *
     * @return bool|string
     */
    public static function recordOperate($operateMessage = '', $operateData = [], $operateWhere = []) {
        if (!is_string($operateMessage) || !is_array($operateData) || (!empty($operateWhere) && !is_array($operateWhere))) {
            return false;
        }
        $data['operate_user_id'] = Yii::$app->user->getId();
        $data['operate_condition'] = !empty($operateWhere) ? json_encode($operateWhere) : '';
        $data['operate_content'] = json_encode($operateData);
        $data['mark'] = $operateMessage;
        return static::insertData($data);
    }
}
